### ISSUE TITLE
Initial M17 issue tracker

### ISSUE THREAD

**Issue by acmeplus** [RK3128-CFW/m17-cfw#1]
- [x] Add proper kernel DTS (not decompiled) to kernel
- [x] Update batocera and buildroot repos to batocera latest versions and create m17-wip branches
- [x] Create buildroot configuration for m17, including BR2_EXTERNAL for batocera packages
- [x] Create firmware installation script
- [x] Investigate why batocera image (idbloader, uboot, trust and two partitions) blocks the boot sequence. Determine correct partition for batocera and buildroot based images
- [ ] Change USB configuration so it can support ADB as well as external controllers, keyboard, etc.
- [ ] Add udev rules to map internal controller as a gamepad/joystick (avoid issues with keyboard input fields)
- [x] Fix: Brightness control is broken
- [x] Add correct also configuration. New rootfs does not have the correct configuration (udev rule missing?)
